all:
	@echo "Command     : Description"
	@echo "----------- : -----------"
	@echo "make vendor : install the dependency package"
	@echo "make run    : run the program"

vendor:
	@dart pub add crypto

run:
	@dart run main.dart
