#!/usr/bin/env python

from enum import Enum

Quality = Enum('Quality', 'Normal Good Better Best', start=0)

Tool = Enum('Tool', {
    'None': 0, # Tool['None']
	'Handaxe': 100,
	'Axe': 200,
	'Hamme': 300,
	'Wate': 400,
	'Hoe': 500,
	'Sickle': 600,
	'Shears': 700,
	'Milke': 800,
	'Brush': 900,
	'Harpoon': 1000,
	'FishingRod': 1100,
	'Flute': 1200,
	'Torch': 1300,
})

Entity = Enum('Entity', [
    'Plant',
    'Tree',
    'Resource',
    'MagneticItem',
    'Player',
    'Inventory',
    'SeedInventory',
    'Currency',
    'ShippingBin',
    'NPC',
    'Weather',
    'Animal',
    'AnimalHerd',
    'GrassStarter',
    'Bed',
    'WildPlantPatch',
    'IrrigationPump',
    'PachaStatue',
    'Nanny',
    'Idea',
    'Building',
    'TallGrass',
    'PickableItem',
    'TileableDecoration',
    'FenceDoor',
    'WaterWell',
    'Decoration',
    'BeeHive',
    'RacingLeague',
    'ReflectionStatue',
    'FirePit',
    'Score',
    'ManualProducer',
    'AutoProducer',
    'StorageBox',
    'Dashboard',
    'SchoolWorkshop',
    'PlantNursery',
    'FollowingPetData',
    'QuestManager',
    'Calendar',
    'IrrigationTrench',
    'IrrigationExtender',
    'TotemOffering',
    'CaveRoom',
    'CaveTorch',
    'CavePaint',
    'Trading',
    'LimitedStockShop',
    'MainStory',
    'UniqueDataManager',
    'Fence',
    'ProsperityObjects',
    'Butcher',
    'TrapSpot',
    'ItemGrower',
    'Olla',
], start=0)
