all:
	@echo
	@echo "Command    : Description"
	@echo "---------- : -----------"
	@echo "make token : List all tokens"
	@echo "make parse : Parse to AST"


token:
	@go run lex-tokens.go

parse:
	@go run parse-ast.go
