all:
	@echo "Command     : Description"
	@echo "----------- : -----------"
	@echo "make vendor : install the dependency package"
	@echo "make run    : run the program"

vendor:
	@cargo build

run:
	@cargo run --quiet
